"""empty message

Revision ID: fdcac2fbbd63
Revises: cbd3cc864392
Create Date: 2023-12-11 20:01:59.723826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdcac2fbbd63'
down_revision = 'cbd3cc864392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_table', sa.Column('raccoon_id', sa.Integer(), nullable=True))
    op.add_column('visit_table', sa.Column('trashcan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_visit_table_raccoon_id_raccoon_table'), 'visit_table', 'raccoon_table', ['raccoon_id'], ['id'])
    op.create_foreign_key(op.f('fk_visit_table_trashcan_id_trashcan_table'), 'visit_table', 'trashcan_table', ['trashcan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_visit_table_trashcan_id_trashcan_table'), 'visit_table', type_='foreignkey')
    op.drop_constraint(op.f('fk_visit_table_raccoon_id_raccoon_table'), 'visit_table', type_='foreignkey')
    op.drop_column('visit_table', 'trashcan_id')
    op.drop_column('visit_table', 'raccoon_id')
    # ### end Alembic commands ###
